### ISSUE TITLE
How is the built static resources being linked to the server side?

### ISSUE THREAD

**Issue by davidsth** [oktadeveloper/spring-boot-angular-example#7]
Hello,
I was looking through the code and didn't see any configuration to copy files from the `dist/` folder to any static location read by spring app:

Seems like spring by default reads from the following locations:
```/META-INF/resources/
/resources/
/static/
/public/
```

**Comment by mraible** [comment]
That's because I expect you to deploy this as two separate applications. If you'd rather package everything in the same application, I'd recommend you take a look at [JHipster](http://www.jhipster.tech).
